# Config file for travis-ci.org

language: php
php:
  - "nightly"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
matrix:
  allow_failures:
    - php: "nightly"
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install:
  - if [[ $TRAVIS_PHP_VERSION > '7.1' || $TRAVIS_PHP_VERSION = nightly ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' || $TRAVIS_PHP_VERSION = nightly ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi
  - sh travis.sh
script:
  - cd _test
  - phpunit --configuration=../lib/plugins/swarmwebhook/phpunit.xml --group plugin_swarmwebhook --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover --repository=g/$TRAVIS_REPO_SLUG --revision=$TRAVIS_COMMIT
