<?php

namespace dokuwiki\plugin\swarmzapierstructwebhook\test\mock;


class IFTTT extends \dokuwiki\plugin\swarmzapierstructwebhook\webhooks\IFTTT
{
    public function parseTimeIntoTimestamp($timestring, $nowTS)
    {
        return parent::parseTimeIntoTimestamp($timestring, $nowTS); // TODO: Change the autogenerated stub
    }

}