<?php

namespace dokuwiki\plugin\swarmwebhook\test\mock;


class IFTTT extends \dokuwiki\plugin\swarmwebhook\webhooks\IFTTT
{
    public function parseTimeIntoDateTime($timestring, $nowTS)
    {
        return parent::parseTimeIntoDateTime($timestring, $nowTS); // TODO: Change the autogenerated stub
    }

}