<?php

namespace dokuwiki\plugin\swarmzapierstructwebhook\test\mock;

class Zapier extends \dokuwiki\plugin\swarmzapierstructwebhook\webhooks\Zapier
{
    public function handleWebhookPayload($json)
    {
        return parent::handleWebhookPayload($json);
    }

    public function extractDataFromPayload(array $data)
    {
        return parent::extractDataFromPayload($data); // TODO: Change the autogenerated stub
    }


}